language: node_js
node_js:
  - "5.2.0"

before_script:
  - npm install -g gulp
script: gulp jest

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
env:
  CXX=g++-4.8

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/7daa092b0d07ac7b28e3
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always